### ISSUE TITLE
Use Jekyl 3.3 root path

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/styles#112]
https://github.com/blog/2277-what-s-new-in-github-pages-with-jekyll-3-3

**Comment by rgaiacs** [comment]
I think that we implemented that. @gvwilson If I'm wrong please reopen it.

**Comment by gvwilson** [comment]
We haven't implemented this yet as far as I know.

**Comment by wking** [comment]
On Fri, Jan 13, 2017 at 11:27:30AM -0800, Raniere Silva wrote:
> I think that we implemented that. @gvwilson If I'm wrong please reopen it.

I don't think so:

  $ git describe --always
  5e89d32
  $ grep -B3 root: bin/lesson_initialize.py
  # Set the default layout for things in the episodes collection.
  defaults:
    - values:
        root: ..
  --
  ROOT_INDEX_MD = '''\
  ---
  layout: lesson
  root: .

With Jekyll 3.3 we no longer need to set those on a per-page basis.

  $ git grep page.root | head -n3
  _includes/all_keypoints.html:        <a href="{{ page.root }}{{ episode.url }}">{{ episode.title }}</a>
  _includes/carpentries.html:    <a href="{{ site.swc_site }}"><img src="{{ page.root }}/assets/img/swc-icon-blue.svg" alt="Software Carpentry logo" /></a>
  _includes/carpentries.html:    <a href="{{ site.dc_site }}"><img src="{{ page.root }}/assets/img/dc-icon-black.svg" alt="Data Carpentry logo" /></a>

And these page.root instances should be replaced with a relative_url
filter.  The resulting links will be relative to the domain root
(e.g. /styles/assets/…) and not fully relative (e.g. ../assets/…), but
the dev server works around that for you [1].  So the generated
content will not be quite as nice as what we have now (because you
can't rsync the compiled output an arbitrary location), but the links
will be easier to maintain (no need to muck with per-page settings).

[1]: http://jekyllrb.com/news/2016/10/06/jekyll-3-3-is-here/#siteurl-is-set-by-the-development-server

**Comment by wking** [comment]
We also had a discussion on the various relative/absolute URL
approaches in [1], but that repo appears to no longer exist.
@gvwilson, do you remember if you deleted that repository or moved it
somewhere else?

[1]: https://github.com/gvwilson/new-lesson-example/pull/27

**Comment by rgaiacs** [comment]
I'm closing this since I did some changes to avoid `root` in YAML.
