### ISSUE TITLE
bin/lesson_initialize.py should be marked executable

### ISSUE THREAD

**Issue by mr-c** [swcarpentry/styles#144]
Or https://github.com/swcarpentry/lesson-example/blob/gh-pages/setup.md should be updated to say `python bin/lesson_initialize.py`

**Comment by rgaiacs** [comment]
`bin/lesson_initialize.py` is already marked executable:

$ git rev-parse HEAD
895499e6df8747839488bead870e95715b75e106
$ ls -l bin/lesson_initialize.py 
-rwxr-xr-x 1 raniere raniere 11196 Mar 31 16:12 bin/lesson_initialize.py*
$ chmod a+x bin/lesson_initialize.py 
$ git status bin 
On branch styles
nothing to commit, working tree clean
~~~

@mr-c Thanks for your issue. I'm closing this since looks like it is already fixed. If this is something related with Windows, because Windows file system doesn't have permissions, please open another issue.
