### ISSUE TITLE
Can we add the sell-novice-es and git-novice-es to the repo, the translations are ready

### ISSUE THREAD

**Issue by orchid00** [swcarpentry/styles#180]
@rgaiacs is this the right place to add this?

Can we add the sell-novice-es and git-novice-es to the repo, the translations are ready

@map0logo can help with this

**Comment by rgaiacs** [comment]
@orchid00 I didn't understood what you want.

If you are looking to have a Spanish version of the files at https://github.com/swcarpentry/styles/blob/gh-pages/_includes/ I would recommend to have https://github.com/carpentries/styles-es/ for it. We could use branches but my experience shows that people don't find branches. And because GitHub issue track sucks when compared to Bugzilla to notify core contributors would be very annoying for people to have issues of different languages at the same place.

**Comment by orchid00** [comment]
Yup, right, styles is not the right place. You can delete this isuue.

I'm not in charge of this part, you will get an email from Erin or Francisco or maybe Jonah about rendering the translations from the shell and git lessons to the carpentries repo. The idea is to make them public.

**Comment by rgaiacs** [comment]
Please use https://github.com/swcarpentry/website/issues/867 for further discussion about this.
