### ISSUE TITLE
Update deck.js

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/styles#26]
We want that space bar and backspace keys to work like left and right. This problem was reported at https://github.com/swcarpentry/slideshows/pull/22 and this feature was already implemented upstream, https://github.com/imakewebthings/deck.js/issues/179.

@twitwi could you help us with that?

**Comment by twitwi** [comment]
I'll have a look.
I'm at a conference today, but I might sqeeze in some time during some 
talks.
If not, what would be a deadline? (I'm very busy these 10 days).

My guess is that it is not about an older version.
It may be "because" of browsercast, where the spacebar is rerouted to 
play/pause.

Rémi

**Comment by twitwi** [comment]
Let's use this issue as "update browsercast once it is fixed"

See https://github.com/twitwi/deck.browsercast.js/issues/7

**Comment by r-gaia-cs** [comment]
> I'll have a look.

Thanks.

> I'm at a conference today

Enjoy the conference.

> If not, what would be a deadline?

This hasn't a high priority to be fixed.

> My guess is that it is not about an older version.
> It may be "because" of browsercast, where the spacebar is rerouted to play/pause.

Thanks for this information.

**Comment by twitwi** [comment]
@r-gaia-cs, fixed by #30
