### ISSUE TITLE
Use CSS preprocessor

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/styles#33]
Since we are using [Bootstrap](http://getbootstrap.com/) maybe we could [compile](http://getbootstrap.com/getting-started/#grunt) our own version of the CSS so it will be small and also include our customization.

@wking What do you think of this?

**Comment by r-gaia-cs** [comment]
@gvwilson I'm think in have some fun working on this issue over the weekend and want to check if you are OK with it as describe below.

1. Have a branch `dev` where we store the **patched** source files of Bootstrap.

   1. Edit Bootstrap compile rules to drop the parts that we don't use.
   2. Edit default CSS rules from Bootstrap style to cover our needs. **This includes the changes on the CSS files present at http://github.com/gvwilson/using-jekyll/**.
2. Keep the branch `master` with only the compiled version of the CSS.

**Comment by gvwilson** [comment]
@r-gaia-cs what does compiling our own CSS save us down the road except 
a little bit of disk space?

Thanks,
Greg

p.s. everything that was in using-jekyll is now in the using-jekyll 
branch of lesson-template, so please get new CSS from there.

**Comment by r-gaia-cs** [comment]
>  what does compiling our own CSS save us down the road except a little bit of disk space?

Instead of

~~~
    <link rel="stylesheet" type="text/css" href="css/bootstrap/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="css/bootstrap/bootstrap-theme.css" />
    <link rel="stylesheet" type="text/css" href="css/swc.css" />
~~~

we can have

~~~
    <link rel="stylesheet" type="text/css" href="css/swc.css" />
~~~

and avoid overwrite CSS properties.

**Comment by gvwilson** [comment]
That feels like a fairly small gain whose cost is a significant increase 
in the complexity of our tooling, but I am not a web expert.

**Comment by pbanaszkiewicz** [comment]
@gvwilson:
> That feels like a fairly small gain whose cost is a significant increase
in the complexity of our tooling, but I am not a web expert.

Another very positive aspect of switching to CSS preprocessor is that you can use Sass/Lass/Compass/whatever. Sass to CSS is like Django Template Language is to HTML: you can use variables and such, and it makes writing CSS less painful.

Bootstrap is distributed with its Lass sources so that it's easy to plug in your own styles. But I'd switch to Lass only if we had quite a few of styles. AMY, for example, has very few styles of its own, so I do not consider switching to CSS preprocessor there.

Another solution, instead of using a preprocessor, that could limit number of our CSS files is a simple CSS concatenation. We'd lose advantages that Lass brings, but the result would be similar to what @r-gaia-cs wants.

Cheers,
Piotr

**Comment by r-gaia-cs** [comment]
I remember one of the reasons that I want that. Pandoc only support one CSS file when converting to EPUB. Improve the CSS with a preprocessor seens more easy than send a pull request to Pandoc.
