### ISSUE TITLE
make serve versus bundle exec jekyll serve

### ISSUE THREAD

**Issue by kelseygonzalez** [swcarpentry/styles#476]
For windows 10, `make serve` fails for me but `bundle exec jekyll serve` runs. (Thanks for your help, @zkamvar @Denubis @ldko and @maxim-belkin on getting this figured out). It sounds like the instruction section "For Everyone" needs to be updated to reflect this if it's a more general issue for all Windows computers.

**Comment by fmichonneau** [comment]
I've transferred this issue to the styles repository. We'll review the PR that Brian has put in once it's in this repo. 

Regarding the message from Ruby Sass, we rely on the gems that come as dependencies from GitHub Pages and so this is outside our control. However, this dependency issue should get fixed in the near future.

**Comment by Denubis** [comment]
created conversation #480 from this. Short version: patching hard-coded bash locations out of a makefile is not an effective measure if we can't test if it works. Let's discuss what we want our testing framework to look like first?

**Comment by fmichonneau** [comment]
I think the Makefile has been greatly improved since this discussion. Feel free to re-open or create a new issue if something like this happens again.
