### ISSUE TITLE
Fixing lesson deployment scripting: Travis-CI for all OSes, better choices than makefiles, reducing languages?

### ISSUE THREAD

**Issue by Denubis** [swcarpentry/styles#480]
As per request on https://github.com/carpentries/lesson-example/pull/293 migrating here

Issues.
1. We do not have Travis-CI checks on our deployment system for all OSes, leading to claims of "it works for me."
2. We require bash, ruby, python, and R as part of our deployment system and we have no deployment script that is tested in travis-ci
3. Our makefile is incredibly complex with a bunch of hardcoded things like bash's location.

Before I redo my work here, we should probably chat about what our desired deployment and testing infrastructures are. I'm a big fan of having package managers as part of this, since scoop (windows), brew (macOS) and apt (ubuntu) are all robust.

Therefore: what would a correct TravisCI testing harness for our script creation file look like? Are we tied to the unmaintainable make syntax? Would we be better served from a ground-up rewrite in a slightly more modern build environment? Do we *really* need 4 programming languages and package managers as part of lesson deployment, and if so, can we turn deployment into a scripted thing so that we don't have multiple (contradictory) sources of truth on how to compile lessons locally?

Discuss.

**Comment by fmichonneau** [comment]
Hi @Denubis,

Maxim has created new GitHub actions that allow us to comprehensively check changes on the styles template on a few lessons across OSes. How does that align with what you had in mind?

Thanks!

**Comment by Denubis** [comment]
Do these actions perform installs of the 4 different programming languages on each OS? (I.e. can we render and lesson-check an R-markdown lesson?) And are those scripts runnable by normal folk, so we can reduce the complexity of our install requirements?

**Comment by zkamvar** [comment]
Hi @Denubis, François is away this week, but I can take a stab at answering your questions. The answer to your first and second questions are yes and no (with a but), respectively. 

The CI service runs on all OSes and is able to have all of the programming languages installed, which you can see here: https://github.com/carpentries/styles/blob/gh-pages/.github/workflows/template.yml#L15

Your question of "And are those scripts runnable by normal folk, so we can reduce the complexity of our install requirements?" is tricky because while the CI installs the software in a clean environment with full root access, normal users are not always going to have such luxury, largely because they will be coming in with older versions of these software already installed. The [setup instructions] have recently been overhauled with this in mind, but again, it's tricky.

Some months ago, I set up a [docker container] to reduce this complexity down to needing to install only docker, and it has worked for some people, but it's definitely not a perfect solution (e.g. it doesn't work for people on Windows who haven't been able to install the Windows 10 v 2002 update).

For what it's worth, we are working on overhauling the requirements for the template and will be piloting it soon.

[setup instructions]: https://carpentries.github.io/lesson-example/setup.html
[docker container]: https://github.com/carpentries/lesson-docker#docker-container-for-lesson-maintenance

**Comment by fmichonneau** [comment]
I'm going to close this given that we have mostly move away from Travis, that GitHub Actions implements checks to the styles repo across multi OSes, that there have been many improvements to the Makefile, and we are making good progress towards the next iteration of the lesson infrastructure. Feel free to open new issues related to these topics as needed. Thanks!
