### ISSUE TITLE
No Default CRAN 

### ISSUE THREAD

**Issue by dafnidrake** [swcarpentry/styles#526]
When trying to use `make serve` to preview changes locally, I was receiving the following error:
``` 
Error in contrib.url(repos, "source") :
    trying to use CRAN without setting a mirror
Calls: install_required_packages -> install.packages -> contrib.url
Execution halted
make: *** [install-rmd-deps] Error 1
```

I was able to resolve by setting my default CRAN mirror following a suggestion from @zkamvar by adding `options(repos = c(CRAN = "https://cran.rstudio.org"))` to my `.Rprofile`, but others may be running into similar issues.

**Comment by zkamvar** [comment]
Thank you for reporting this @drakeasberry. I can take it from here.

Turns out it's my own darn fault. I tried to fix this issue in #509, but it turns out that I was being a numpty. The "repos" option ALWAYS has a value. If the repo is unset, it defaults to `"@CRAN@"`, which signals `contrib.url()` to give the user an interactive prompt to choose the mirror.

I'll make a PR that should fix this once and for all :triumph:
