### ISSUE TITLE
Syncing lessons with styles repository

### ISSUE THREAD

**Issue by josephmje** [swcarpentry/styles#598]
When syncing lessons with this repository, the `_includes`, `assets` and `_layouts` folders were previously left out. Recently, the following files are included when synced:

- ` _includes/base_path.html`
- `_includes/javascript.html`
- `_includes/links.md`
- `_layouts/base.html`
- `assets/css/katex.min.css`
- `assets/css/lesson.scss`
- `assets/js/katex.min.js`

I just wanted to confirm whether this change is correct?

Thank you!

**Comment by maxim-belkin** [comment]
The goal of the remote theme is to gather all the bells and whistles (CSS, JS, HTML templates) in one place so that we can do
```yaml
remote_theme: carpentries/carpentries-theme
```
in the `_config.yml` and be done with it. Remote themes are described here: https://jekyllrb.com/docs/themes/#creating-a-gem-based-theme There you can find the following paragraph:

> For example, if your theme has a `/_layouts/page.html` file, and a page has layout: page in its front matter, Jekyll will first look to the site’s `_layouts` folder for the page layout, and if none exists, will use your theme’s page layout.

So, it seems that having the files you list above in the lesson itself is not a problem but I think they will be in the carpentries-theme repo once it's updated.

**Comment by josephmje** [comment]
Thanks for the explanation @maxim-belkin! We've gone ahead and decided to keep them out of the above lesson since they will be pulled in anyway from the remote theme.
