### ISSUE TITLE
css for SQL lessons

### ISSUE THREAD

**Issue by orchid00** [swcarpentry/styles#9]
Hi, 
I have some suggestions on the template for the SQL lessons:

Padding:
*I see that most if not all tables need a bit more of bottom padding, the letters in the next paragraph are too close.
*Challenges on the other side are very spacious in between, and probably the question title should be a bit smaller.
Colors:
*Table headers, I don't know if it is just me, but that blue is too dark to be combined with black... just saying...

This is a duplicate from:
https://github.com/swcarpentry/sql-novice-survey/issues/27
suggested by Raniere Silva to be copied here.

**Comment by pbanaszkiewicz** [comment]
Hi, @orchid00. I can't find challenges in the repository with lesson on SQL. Can you point me at them?

**Comment by gvwilson** [comment]
http://github.com/swcarpentry/sql-novice-survey has a bunch of challenges.

**Comment by pbanaszkiewicz** [comment]
@gvwilson do you both mean "FIXME"s?

**Comment by orchid00** [comment]
I meant the font of the titles called "challenges" so all of them. It is a matter of style: they are very spacious in between, and probably the question title (where it says fixme) should be a bit smaller. Is that clearer?

**Comment by pbanaszkiewicz** [comment]
Thanks @orchid00 and @gvwilson. My fork, for reason unknown to me, contained "FIXME" headers instead of proper challenges as, for example, here http://swcarpentry.github.io/sql-novice-survey/01-select.html (at the bottom).

I've pulled in the recent changes and will work on styles some more.

**Comment by pbanaszkiewicz** [comment]
Hi everyone,

I don't like that light-green color of challenge boxes. I'd get rid of it, and to highlight that this section is a challenge I'd put it under "Challenge" (or "Exercise") header.

BEFORE:
![screenshot from 2015-02-14 12 12 50](https://cloud.githubusercontent.com/assets/72821/6199417/d61bed0c-b442-11e4-93b0-d1c508cd5bff.png)

AFTER:
![screenshot from 2015-02-14 12 12 17](https://cloud.githubusercontent.com/assets/72821/6199418/d99f6594-b442-11e4-9ecf-2bfd4b7b54b5.png)

Pros:

* clear indicator that this section is intended as an exercise for reader
* proper heading structure (each challenge is a subsection of "Challenges")
* visually more appealing

Cons:

* requires changes to lesson files

What do you think?

**Comment by orchid00** [comment]
Good idea to remove the green boxes!
Btw, I am looking at version 5.3, and the headers of the tables are different than yours. have a look:
![css_sw_ugly](https://cloud.githubusercontent.com/assets/9795785/6199621/3ac77bc4-b49b-11e4-8705-6681636faf05.png)
Can you modify that too?

**Comment by pbanaszkiewicz** [comment]
@orchid00 I accidentially showed you a lesson with #10 applied - it changes tables a bit, now they're similar to what Bootstrap [offers](http://getbootstrap.com/css/#tables-bordered).

What do you think about that additional header "Challenges"? Should I keep it or throw away?

**Comment by orchid00** [comment]
Oh! tables look much better like that.
To be honest, I'm very picky and and I don't think much ppl will notice those things, but here you go:
now that you removed the green highlight the left padding looks a bit off. If you put everything aligned to the Challenges (header) it would look better, in that case keep it.

Also, we talked with some other instructors that the challenges should come more often and not only at the end of the lesson. But I guess that is a more structural change. In that case wouldn't be necessary to write challenge headers :P

**Comment by pbanaszkiewicz** [comment]
> To be honest, I'm very picky and and I don't think much ppl will notice those things, but here you go:
now that you removed the green highlight the left padding looks a bit off. If you put everything aligned to the Challenges (header) it would look better, in that case keep it.

With left margin removed:
![screenshot from 2015-02-14 15 37 49](https://cloud.githubusercontent.com/assets/72821/6199927/8ae1ef54-b45f-11e4-853a-bf3130668143.png)

> Also, we talked with some other instructors that the challenges should come more often and not only at the end of the lesson.

Oh I really like this change.

> But I guess that is a more structural change. In that case wouldn't be necessary to write challenge headers :P 

You're right. This gives me an idea of how to bring nice-looking exercises inside the lesson's content.

Take a look at this "Note" section [here](http://wrapt.readthedocs.org/en/latest/examples.html#thread-synchronization): it looks like a box with a header, but it's not disturbing.

I'm thinking a similar style for challenges: it has to be a box, because challenges sometimes get more than one paragraph of text, and it must not be disturbing, ie. header should be fairly small and colors not too bright.

I'll probably throw away my [previous](https://github.com/swcarpentry/styles/issues/9#issuecomment-74371247) changes to challenges and prepare something that presents these exercises nicely and inline, not at the end of the lesson.

**Comment by orchid00** [comment]
Yeah the box with the header looks OK. I think before it was just the color green that didn't look so nice. 

Again, I see something different, your queries are now in grey-ish? and my queries are color green...

**Comment by pbanaszkiewicz** [comment]
> Again, I see something different, your queries are now in grey-ish? and my queries are color green...

The queries in grey-ish had no `class="sql"` (` {.sql}` in Markdown) - good catch. This is an issue for sql-novice-survey, you can send a PR if you want.

**Comment by orchid00** [comment]
@pbanaszkiewicz (I'm new here) where should I do the PR?

**Comment by pbanaszkiewicz** [comment]
@orchid00 that's alright. I think the issue is that code blocks in challenges miss `{.sql}`. I've found a couple of lessons that do not have it:

* http://swcarpentry.github.io/sql-novice-survey/01-select.html
* http://swcarpentry.github.io/sql-novice-survey/03-filter.html
* http://swcarpentry.github.io/sql-novice-survey/05-null.html

Here's an issue ticket I've just created: https://github.com/swcarpentry/sql-novice-survey/issues/34

Please send a PR to the https://github.com/swcarpentry/sql-novice-survey/ repository.
