### ISSUE TITLE
Add an example Rmd file to _episodes_rmd

### ISSUE THREAD

**Issue by tracykteal** [swcarpentry/styles#98]
It would be good to have an example Rmd file in _episodes_rmd. Then you could also try out the  make script.

**Comment by andreabedini** [comment]
@tracykteal I had a go. Baby steps.

**Comment by gvwilson** [comment]
If this is merged, then every lesson that uses the template will include this `.rmd` file, which means that everyone who wants to build a lesson locally will need to install R - even people who are working on lessons that aren't R-based.  @fmichonneau added `_episodes_rmd/06-rmarkdown-example.Rmd` to [the example lesson](http://github.com/swcarpentry/lesson-example/) on the assumption that anyone wanting to work on lessons would probably have it on their hard drive for reference (since it documents the lesson format using the lesson format). Does that satisfy this requirement?

**Comment by andreabedini** [comment]
@gvwilson I am glad the two minutes it took me to send a pull-request brought this up :)
